### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JokerQyou** [pagecho/maupassant#13]
May I ask what is the license for this theme? The hexo fork seems to be using MIT license, but all the other forks including this original one do not contain any license information.

**Comment by ralsina** [comment]
Yes, please add a license!

I have ported it to Nikola (see https://themes.getnikola.com/v7/maupassant/ ) and I would love to give proper attribution and respect your license.

**Comment by pagecho** [comment]
eh....sorry folks, I forgot....
MIT license

**Comment by ralsina** [comment]
Neat, thanks :-)
