### ISSUE TITLE
把主题移植到了Ghost

### ISSUE THREAD

**Issue by LjxPrime** [pagecho/maupassant#3]
https://github.com/LjxPrime/maupassant
请问这样做可以吗，如果不可以我会马上删除。

**Comment by pagecho** [comment]
嗯，当然没问题，而且非常欢迎 : )

**Comment by tufu9441** [comment]
@pagecho 我最近修改并分享了一个Hexo的版本，望允许，https://github.com/tufu9441/maupassant-hexo
